package org.uma.jmetal.auto.autoconfigurablealgorithm.examples;

import org.uma.jmetal.auto.autoconfigurablealgorithm.AutoRVEA;
import org.uma.jmetal.component.algorithm.EvolutionaryAlgorithm;
import org.uma.jmetal.solution.doublesolution.DoubleSolution;
import org.uma.jmetal.util.JMetalLogger;
import org.uma.jmetal.util.fileoutput.SolutionListOutput;
import org.uma.jmetal.util.fileoutput.impl.DefaultFileOutputContext;

/**
 * Class configuring RVEA using arguments in the form <key, value> and the {@link AutoRVEA} class.
 * The problem is solved twice: first with the reference vectors generated by default (105 for
 * three objectives) and then with the 100 vectors of file {@code W3D_100.dat}; the population
 * size is the number of reference vectors in both cases.
 *
 * @author Antonio J. Nebro (ajnebro@uma.es)
 */
public class RVEAConfiguredFromAParameterString {

  public static void main(String[] args) {
    String referenceFrontFileName = "resources/referenceFrontsCSV/DTLZ2.3D.csv";

    String parameters =
        "--problemName org.uma.jmetal.problem.multiobjective.dtlz.DTLZ2 "
            + "--randomGeneratorSeed 12 "
            + "--referenceFrontFileName "
            + referenceFrontFileName
            + " "
            + "--maximumNumberOfEvaluations 40000 "
            + "--algorithmResult population "
            + "--createInitialSolutions random "
            + "--variation crossoverAndMutationVariation "
            + "--offspringPopulationSize 100 "
            + "--crossover SBX "
            + "--crossoverProbability 1.0 "
            + "--crossoverRepairStrategy bounds "
            + "--sbxDistributionIndex 30.0 "
            + "--mutation polynomial "
            + "--mutationProbabilityFactor 1.0 "
            + "--polynomialMutationDistributionIndex 20.0 "
            + "--mutationRepairStrategy bounds "
            + "--selection random "
            + "--replacement rvea "
            + "--alpha 2.0 "
            + "--fr 0.1 ";

    run(parameters.split("\\s+"), "FUN.RVEA.defaultVectors.csv");

    String parametersWithVectorsFile =
        parameters + "--referenceVectorsFile resources/weightVectorFiles/moead/W3D_100.dat";
    run(parametersWithVectorsFile.split("\\s+"), "FUN.RVEA.W3D_100.csv");
  }

  private static void run(String[] parameters, String funFileName) {
    var autoRVEA = new AutoRVEA();
    autoRVEA.parse(parameters);

    AutoRVEA.print(autoRVEA.fixedParameterList());
    AutoRVEA.print(autoRVEA.configurableParameterList());

    EvolutionaryAlgorithm<DoubleSolution> rvea = autoRVEA.create();
    rvea.run();

    JMetalLogger.logger.info("Total computing time: " + rvea.totalComputingTime());
    JMetalLogger.logger.info("Number of solutions found: " + rvea.result().size());

    new SolutionListOutput(rvea.result())
        .setFunFileOutputContext(new DefaultFileOutputContext(funFileName, ","))
        .print();
  }
}
